# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: programl/proto/program_graph.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'programl/proto/program_graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from programl.third_party.tensorflow import features_pb2 as programl_dot_third__party_dot_tensorflow_dot_features__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"programl/proto/program_graph.proto\x12\x08programl\x1a.programl/third_party/tensorflow/features.proto\"\xb8\x01\n\x0cProgramGraph\x12\x1c\n\x04node\x18\x01 \x03(\x0b\x32\x0e.programl.Node\x12\x1c\n\x04\x65\x64ge\x18\x02 \x03(\x0b\x32\x0e.programl.Edge\x12$\n\x08\x66unction\x18\x04 \x03(\x0b\x32\x12.programl.Function\x12 \n\x06module\x18\x05 \x03(\x0b\x32\x10.programl.Module\x12$\n\x08\x66\x65\x61tures\x18\x06 \x01(\x0b\x32\x12.programl.Features\"\xbd\x01\n\x04Node\x12!\n\x04type\x18\x01 \x01(\x0e\x32\x13.programl.Node.Type\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x66unction\x18\x04 \x01(\x05\x12\r\n\x05\x62lock\x18\x07 \x01(\x05\x12$\n\x08\x66\x65\x61tures\x18\x08 \x01(\x0b\x32\x12.programl.Features\"=\n\x04Type\x12\x0f\n\x0bINSTRUCTION\x10\x00\x12\x0c\n\x08VARIABLE\x10\x01\x12\x0c\n\x08\x43ONSTANT\x10\x02\x12\x08\n\x04TYPE\x10\x03\"\xb4\x01\n\x04\x45\x64ge\x12!\n\x04\x66low\x18\x01 \x01(\x0e\x32\x13.programl.Edge.Flow\x12\x10\n\x08position\x18\x02 \x01(\x05\x12\x0e\n\x06source\x18\x03 \x01(\x05\x12\x0e\n\x06target\x18\x04 \x01(\x05\x12$\n\x08\x66\x65\x61tures\x18\x05 \x01(\x0b\x32\x12.programl.Features\"1\n\x04\x46low\x12\x0b\n\x07\x43ONTROL\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x12\x08\n\x04\x43\x41LL\x10\x02\x12\x08\n\x04TYPE\x10\x03\"N\n\x08\x46unction\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06module\x18\x02 \x01(\x05\x12$\n\x08\x66\x65\x61tures\x18\x03 \x01(\x0b\x32\x12.programl.Features\"<\n\x06Module\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\x08\x66\x65\x61tures\x18\x02 \x01(\x0b\x32\x12.programl.FeaturesB/\n\x0c\x63om.programlB\x11ProgramGraphProtoP\x01Z\nprogramlpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'programl.proto.program_graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\014com.programlB\021ProgramGraphProtoP\001Z\nprogramlpb'
  _globals['_PROGRAMGRAPH']._serialized_start=97
  _globals['_PROGRAMGRAPH']._serialized_end=281
  _globals['_NODE']._serialized_start=284
  _globals['_NODE']._serialized_end=473
  _globals['_NODE_TYPE']._serialized_start=412
  _globals['_NODE_TYPE']._serialized_end=473
  _globals['_EDGE']._serialized_start=476
  _globals['_EDGE']._serialized_end=656
  _globals['_EDGE_FLOW']._serialized_start=607
  _globals['_EDGE_FLOW']._serialized_end=656
  _globals['_FUNCTION']._serialized_start=658
  _globals['_FUNCTION']._serialized_end=736
  _globals['_MODULE']._serialized_start=738
  _globals['_MODULE']._serialized_end=798
# @@protoc_insertion_point(module_scope)
